name: CI (build, lint, test)
# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Ubuntu/Node.js v18
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint monorepo root
        run: pnpm run lint

      - name: Build, lint, test all packages
        run: pnpm turbo lint build test

  integration-tests:
    needs: build
    name: Integration Tests
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    services:
      devnet:
        image: kadena/devnet
        options: >-
          --memory 7g
          --cpus 2
          --health-cmd "curl --verbose --fail http://localhost:8080/info || exit 1"
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: run integration tests
        run: pnpm run test:integration
  e2e-tests:
    name: end-to-end tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ "@kadena/tools" ]

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install browsers
        run: pnpm --filter @kadena-dev/e2e-tests run install:chromium
        working-directory: packages/tools/e2e-tests

      - name: Build
        run: pnpm run build
        env:
          # Dummy values for faucet transactions.
          FAUCET_PUBLIC_KEY: 782127638ab9cc8fa8598ff0120464ceef6f367ddcd616b47afffbdb175dcc5e
          FAUCET_PRIVATE_KEY: 93fd78bd1e79a3b593d4732b76050b418aeefa5e4e6ea80f351b4c3a5b0dd19f

      - name: Run Playwright tests
        run: pnpm run test:e2e -- --project=${{ matrix.package }}
        env:
          CI: true
          TESTOBJECT: ${{ matrix.package }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: packages/tools/e2e-tests/playwright-report/
          retention-days: 30
