name: Docs - CI

on:
  push:
    paths:
      - packages/apps/kadena-docs/**

jobs:
  cypress-regression:
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: fetch vercel url
        env:
          VERCEL_TOKEN: ${{ secrets.vercel_kadenajs_gh_token }}
          GIT_SHA: ${{ github.sha }}
          PROJECT_ID: ${{ secrets.vercel_projectid_docs }}
        run: |
          echo "Sleeping a bit to ensure Vercel has kicked off build (this should be a hook tbh)"
          sleep 10
          PREVIEW_URL=$(curl -H "Content-type: application/json" -H "Authorization: Bearer $VERCEL_TOKEN" "https://api.vercel.com/v5/deployments?teamId=kadena-js&projectId=$PROJECT_ID&state=BUILDING,READY&target=preview" | jq --arg commit_sha "$COMMIT_SHA" -r '.deployments[] | select(.meta.githubCommitSha == $commit_sha ) | .url ')
          echo $PREVIEW_URL
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV
      - name: npx cypress run
        working-directory: packages/apps/kadena-docs
        run: |
          npm install
          npx cypress run --config baseUrl="${{ env.PREVIEW_URL }}"
      
