name: Docs Cypress tests

on:
  push:
    paths:
      - packages/apps/kadena-docs/*/**

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: pnpm build
        run: pnpm run build --filter @kadena/docs

      - name: Create page tree JSON
        run: pnpm run build:scripts
        working-directory: packages/apps/docs

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: packages/apps/docs
          start: npm run dev
          browser: chrome
          install: false
          wait-on: 'http://localhost:3000'
        env:
          # pass GitHub token to detect new build vs re-run build
          NEXT_PUBLIC_APP_DEV: test
