name: Visual Regression Tests
# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  push:
  workflow_dispatch:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  visual-regression-tests:
    name: Visual Regression Tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: packages/libs/react-ui
            projectToken: 'REACT_UI_CHROMATIC_TOKEN'
          - package: packages/apps/docs
            projectToken: 'DOCS_CHROMATIC_TOKEN'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history, needed to determine diffs.
          show-progress: false

      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            pathFilter:
                - '${{ matrix.package }}/**'

      - uses: pnpm/action-setup@v2
        with:
          version: 8


      - uses: actions/setup-node@v3
        if: steps.changed.outputs.pathFilter == 'true'
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        if: steps.changed.outputs.pathFilter == 'true'
        run: pnpm install

      - name: Build
        if: steps.changed.outputs.pathFilter == 'true'
        run: pnpm run build

      - name: Publish Storybook
        if: steps.changed.outputs.pathFilter == 'true'
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          exitOnceUploaded: true
          buildScriptName: 'build:storybook'
          projectToken: ${{ secrets[matrix.projectToken] }}
          workingDir: ${{ matrix.package }}
          autoAcceptChanges: 'main'
          onlyChanged: true # 👈 Required option to enable TurboSnap
